import type { DrugEntry, Interaction } from "./drugCheck";

// Pharmacist-verified medication-safety reference (19 drugs, 13 interactions),
// curated + safety-reviewed via a multi-agent pass. Cited to BNF / NICE / Stockley’s /
// MOH Malaysia. Class tokens (klass) + interaction endpoints are normalised so the
// pairwise checker (drugCheck) can match. REFERENCE ONLY — never prescribing.
export const DRUGS: DrugEntry[] = [
  { name: "paracetamol", aliases: ["acetaminophen","pcm","panadol","para","apap"], klass: "analgesic", maxDoseAdult: "4 g/day (max 1 g per dose); reduce if <50 kg, chronic alcohol use, or hepatic impairment", note: "Hepatotoxic in overdose; total from ALL combination products must stay within the daily max — the commonest inadvertent overdose in primary care.", source: "BNF / MOH Malaysia" },
  { name: "ibuprofen", aliases: ["brufen","nurofen","advil","ibuprofin"], klass: "nsaid", maxDoseAdult: "OTC 1.2 g/day; up to 2.4 g/day on prescription", note: "GI bleeding and renal risk; avoid in peptic ulcer, CKD, heart failure and 3rd-trimester pregnancy; 'triple whammy' AKI when combined with an ACEi/ARB plus a diuretic; caution in aspirin-sensitive asthma.", source: "BNF / NICE" },
  { name: "amoxicillin", aliases: ["amoxil","amoxycillin","amox","moxatag"], klass: "penicillin", note: "Contraindicated in penicillin allergy (anaphylaxis risk and cross-reactivity with other beta-lactams); widespread rash if given in glandular fever/EBV or alongside allopurinol.", source: "BNF / MOH Malaysia" },
  { name: "azithromycin", aliases: ["zithromax","azithro","z-pack","azicip"], klass: "macrolide", note: "Prolongs the QT interval — caution with other QT-prolonging drugs or known long-QT; unlike clarithromycin it only weakly inhibits CYP3A4 but still monitor when combined with warfarin.", source: "BNF / Stockley's" },
  { name: "clarithromycin", aliases: ["klacid","clarithro","biaxin"], klass: "macrolide", note: "Strong CYP3A4 inhibitor and QT-prolonging — contraindicated with simvastatin (rhabdomyolysis) and markedly raises levels of warfarin, amlodipine and many other substrates; avoid alongside other QT-prolonging therapy. (Severe.)", source: "Stockley's / BNF / MHRA" },
  { name: "metformin", aliases: ["glucophage","glucophage xr","metformin hcl","metformin hydrochloride"], klass: "biguanide", note: "Lactic acidosis risk — contraindicated if eGFR <30 and review dose at eGFR 30–45; withhold during acute illness, dehydration, sepsis or around iodinated-contrast imaging.", source: "BNF / NICE / MOH Malaysia" },
  { name: "amlodipine", aliases: ["norvasc","amlong","istin","amdepin"], klass: "ccb", maxDoseAdult: "10 mg/day", note: "Dose-dependent ankle oedema (not fluid overload); limit simvastatin to 20 mg/day when co-prescribed because of raised myopathy risk. (Moderate.)", source: "BNF / MHRA" },
  { name: "perindopril", aliases: ["coversyl","perindopril arginine","perindopril erbumine"], klass: "ace inhibitor", note: "Avoid in pregnancy (fetotoxic) and bilateral renal-artery stenosis; hyperkalaemia and AKI risk — monitor U&Es; can cause angioedema and dry cough; avoid with potassium-sparing diuretics/ARB/potassium supplements and beware the NSAID 'triple whammy'.", source: "BNF / NICE" },
  { name: "enalapril", aliases: ["renitec","vasotec","enalapril maleate","enapril"], klass: "ace inhibitor", note: "Same class cautions as perindopril — teratogenic (avoid in pregnancy), hyperkalaemia and renal impairment, angioedema; monitor U&Es and avoid combining with potassium supplements or an ARB.", source: "BNF / NICE" },
  { name: "simvastatin", aliases: ["zocor","simvador","simcard"], klass: "statin", maxDoseAdult: "40 mg/day (80 mg not recommended — myopathy risk)", note: "Myopathy/rhabdomyolysis risk — contraindicated with strong CYP3A4 inhibitors (clarithromycin, erythromycin, itraconazole); cap at 20 mg with amlodipine/diltiazem/verapamil; avoid in pregnancy and active liver disease; avoid grapefruit juice. (Severe with macrolides.)", source: "BNF / MHRA / Stockley's" },
  { name: "atorvastatin", aliases: ["lipitor","atorva","ator","atorvastatin calcium"], klass: "statin", maxDoseAdult: "80 mg/day", note: "Report unexplained muscle pain/weakness (myopathy); avoid in pregnancy and active liver disease; dose limits apply with strong CYP3A4 inhibitors and certain HIV/HCV antivirals — caution with clarithromycin.", source: "BNF / MHRA" },
  { name: "warfarin", aliases: ["coumadin","marevan","warfarin sodium"], klass: "anticoagulant", note: "Narrow therapeutic index — monitor INR; bleeding risk is raised by many common drugs (NSAIDs, aspirin, azole antifungals, macrolides, metronidazole, amiodarone) while others reduce control; teratogenic — avoid in pregnancy. (Severe interactions.)", source: "BNF / Stockley's" },
  { name: "aspirin", aliases: ["asa","acetylsalicylic acid","aspilets","cardiprin","ecosprin","disprin"], klass: "nsaid", maxDoseAdult: "75–150 mg/day (antiplatelet)", note: "Bleeding risk — additive with anticoagulants, other antiplatelets and NSAIDs; avoid in children <16 years (Reye's syndrome); caution in peptic ulcer disease and aspirin-sensitive asthma.", source: "BNF / NICE" },
  { name: "salbutamol", aliases: ["albuterol","ventolin","asthalin","salbutamol sulfate","salbutamol sulphate"], klass: "saba", note: "Frequent or escalating use signals poorly controlled asthma — review preventer therapy; can cause tachycardia, tremor and hypokalaemia (additive with diuretics, corticosteroids and theophylline — monitor potassium in severe/high-dose use).", source: "BNF / GINA / MOH Malaysia" },
  { name: "prednisolone", aliases: ["prednisone","deltacortril","predsol"], klass: "corticosteroid", note: "Do not stop abruptly after prolonged courses (adrenal suppression — taper); raises blood glucose and infection risk, adds to GI-bleed risk with NSAIDs, and causes mood/sleep disturbance; long-term use risks osteoporosis.", source: "BNF / MOH Malaysia" },
  { name: "omeprazole", aliases: ["losec","prilosec","omesec","zimor"], klass: "ppi", note: "CYP2C19 inhibitor — reduces activation of clopidogrel (prefer pantoprazole if a PPI is needed with clopidogrel); long-term use risks hypomagnesaemia and low B12 and may mask gastric malignancy — ensure alarm features are investigated. (Moderate.)", source: "BNF / MHRA" },
  { name: "metronidazole", aliases: ["flagyl","metrogyl","metrizol"], klass: "nitroimidazole", note: "Disulfiram-like reaction with alcohol — avoid all alcohol during treatment and for 48 hours after; potentiates warfarin (raised INR and bleeding). (Severe with alcohol/warfarin.)", source: "BNF / Stockley's" },
  { name: "allopurinol", aliases: ["zyloric","zyloprim","aluron"], klass: "xanthine oxidase inhibitor", note: "Do not start during an acute gout flare (start low, go slow); severe cutaneous reactions (SJS/TEN) with higher risk in HLA-B*58:01 carriers — notably prevalent in Malaysian Chinese, Malay and Indian patients; dangerous marrow suppression with azathioprine/mercaptopurine (avoid or drastically reduce dose). (Severe with azathioprine.)", source: "BNF / MOH Malaysia / Stockley's" },
  { name: "tramadol", aliases: ["tramal","ultram","tramadol hcl","tramadol hydrochloride"], klass: "opioid", note: "Lowers the seizure threshold and can precipitate serotonin syndrome with SSRIs/SNRIs and other serotonergic drugs; additive CNS and respiratory depression with other opioids, benzodiazepines and alcohol; dependence potential.", source: "BNF / MOH Malaysia" },
];

export const INTERACTIONS: Interaction[] = [
  { a: "warfarin", b: "nsaid", severity: "severe", risk: "NSAIDs add antiplatelet effect and cause GI mucosal erosion on top of anticoagulation, markedly raising the risk of serious gastrointestinal and other bleeding.", source: "Stockley's / BNF" },
  { a: "warfarin", b: "macrolide", severity: "severe", risk: "Macrolide inhibition of CYP-mediated warfarin metabolism raises INR and can precipitate major haemorrhage.", source: "Stockley's / BNF" },
  { a: "warfarin", b: "metronidazole", severity: "severe", risk: "Metronidazole inhibits CYP2C9 metabolism of the more potent S-warfarin enantiomer, sharply increasing INR and bleeding risk.", source: "Stockley's / BNF" },
  { a: "nsaid", b: "ace inhibitor", severity: "severe", risk: "Combined loss of renal autoregulation (NSAID reduces afferent flow, ACEi/ARB dilates efferent, diuretic depletes volume) can precipitate acute kidney injury.", source: "NICE / MHRA / BNF" },
  { a: "ace inhibitor", b: "potassium", severity: "severe", risk: "Additive potassium retention can cause dangerous hyperkalaemia and life-threatening arrhythmia, especially with renal impairment.", source: "BNF / NICE" },
  { a: "methotrexate", b: "trimethoprim", severity: "severe", risk: "Additive antifolate action plus reduced renal clearance can cause profound bone-marrow suppression and pancytopenia.", source: "BNF / Stockley's" },
  { a: "simvastatin", b: "clarithromycin", severity: "severe", risk: "Potent CYP3A4 inhibition raises simvastatin exposure, greatly increasing the risk of myopathy and rhabdomyolysis; the statin should be withheld during the course.", source: "BNF / MHRA" },
  { a: "simvastatin", b: "amlodipine", severity: "moderate", risk: "Amlodipine raises simvastatin levels via CYP3A4, so simvastatin should not exceed 20 mg/day to limit myopathy risk.", source: "BNF" },
  { a: "allopurinol", b: "azathioprine", severity: "severe", risk: "Xanthine oxidase inhibition blocks metabolism of active thiopurine metabolites, causing life-threatening myelosuppression unless the thiopurine dose is drastically reduced.", source: "BNF / Stockley's" },
  { a: "metformin", b: "contrast", severity: "moderate", risk: "Contrast-induced acute kidney injury can cause metformin accumulation and lactic acidosis, so metformin is withheld around the procedure with renal monitoring.", source: "NICE / BNF" },
  { a: "ssri", b: "nsaid", severity: "moderate", risk: "SSRI-impaired platelet serotonin combined with NSAID gastric injury increases upper gastrointestinal bleeding risk; consider gastroprotection.", source: "BNF / Stockley's" },
  { a: "tramadol", b: "ssri", severity: "moderate", risk: "Additive serotonergic effect can precipitate serotonin syndrome, and both agents lower the seizure threshold.", source: "BNF / Stockley's" },
  { a: "verapamil", b: "beta-blocker", severity: "severe", risk: "Additive negative chronotropic and inotropic effects can cause severe bradycardia, AV block, and hypotension.", source: "BNF / Stockley's" },
];
