import type { KnowledgeDoc } from "./corpus";

// Curated on-device clinical reference corpus (28 entries). Generated from a
// multi-agent curation pass with a senior-physician safety review — red-flag / when-to-
// refer / safety-netting focus, Malaysian primary-care context, cited to guideline
// families. Reference/educational only; the Knowledge tab labels it as such.
export const CORPUS: KnowledgeDoc[] = [
  {
    id: "chest-pain-emergency-referral-for-suspected-",
    title: "Chest pain — emergency referral for suspected ACS",
    text: "Call emergency services (999) for chest pain (sakit dada) that is severe, lasts more than 15 minutes, radiates to the arm, neck, jaw or back, or comes with sweating, nausea, vomiting or breathlessness (sesak nafas) — treat suspected acute coronary syndrome as an emergency and do not delay transfer to record an ECG. Also admit anyone with cardiac-sounding pain in the last 12 hours or an abnormal or unavailable ECG. Watch for atypical or 'silent' presentations in older people, women and people with diabetes.",
    category: "red-flags",
    source: "NICE CG95 (recent-onset chest pain); MOH Malaysia CPG (acute coronary syndrome)",
    keywords: ["chest pain","sakit dada","ACS","acute coronary syndrome","heart attack","MI","angina","sesak nafas","emergency","999"],
  },
  {
    id: "chest-pain-beyond-the-heart-aortic-dissectio",
    title: "Chest pain beyond the heart — aortic dissection & PE",
    text: "Not all life-threatening chest pain is cardiac: sudden 'tearing' or 'ripping' pain radiating to the back — especially with hypertension or a blood-pressure/pulse difference between the arms — suggests aortic dissection and needs immediate hospital referral. Sudden pleuritic chest pain with breathlessness, a fast heart rate, haemoptysis or a swollen calf points to pulmonary embolism, particularly after surgery, immobility, long travel, active cancer, or in pregnancy and the postpartum period. Both are emergencies — arrange urgent assessment rather than watchful waiting.",
    category: "red-flags",
    source: "NICE CKS (chest pain assessment); ESC guidance",
    keywords: ["aortic dissection","pulmonary embolism","PE","tearing chest pain","pleuritic","DVT","swollen leg","sesak nafas","emergency"],
  },
  {
    id: "acute-breathlessness-sesak-nafas-red-flags",
    title: "Acute breathlessness (sesak nafas) — red flags",
    text: "Arrange emergency assessment for acute breathlessness with any of: SpO2 below 92% on room air, inability to speak in full sentences, cyanosis, exhaustion, confusion or agitation, a silent chest or stridor. Accompanying chest pain, haemoptysis (batuk berdarah) or a single swollen, painful leg raises concern for pulmonary embolism. Do not be reassured by a well-looking patient — track respiratory rate and oxygen saturation, as these change before the patient looks unwell.",
    category: "red-flags",
    source: "NICE CKS (breathlessness)",
    keywords: ["breathlessness","sesak nafas","shortness of breath","SOB","SpO2","hypoxia","stridor","cyanosis","emergency"],
  },
  {
    id: "palpitations-berdebar-red-flags-and-when-to-",
    title: "Palpitations (berdebar) — red flags and when to refer",
    text: "Treat palpitations as an emergency if they occur with syncope, chest pain, severe breathlessness, or signs of heart failure or shock. Refer urgently when palpitations are brought on by exertion or associated with blackouts, when there is known structural or ischaemic heart disease, or a family history of sudden cardiac death under 40 or inherited arrhythmia (e.g. long QT, Brugada, HCM). Aim to capture a 12-lead ECG during symptoms or via ambulatory monitoring, and review the resting ECG for pre-excitation or a prolonged QT interval.",
    category: "referral",
    source: "NICE CKS (palpitations); ESC guidance",
    keywords: ["palpitations","berdebar","arrhythmia","syncope","blackout","sudden cardiac death","WPW","long QT","ECG","referral"],
  },
  {
    id: "haemoptysis-persistent-cough-cancer-and-tb-p",
    title: "Haemoptysis & persistent cough — cancer and TB pathways",
    text: "In anyone aged 40 or over, unexplained haemoptysis (batuk berdarah) warrants urgent referral on a suspected-lung-cancer pathway. In Malaysia, a cough (batuk) lasting 2 weeks or more — especially with haemoptysis, fever (demam), night sweats, weight loss or loss of appetite — must prompt investigation for pulmonary TB (sputum for AFB/GeneXpert and a chest X-ray). Massive or brisk haemoptysis is an airway emergency needing immediate hospital care.",
    category: "referral",
    source: "NICE NG12 (suspected cancer referral); MOH Malaysia CPG (management of TB); WHO",
    keywords: ["haemoptysis","batuk berdarah","cough","batuk","lung cancer","tuberculosis","TB","GeneXpert","night sweats","referral"],
  },
  {
    id: "safety-netting-after-chest-pain-or-cardiac-s",
    title: "Safety-netting after chest pain or cardiac symptoms",
    text: "When a patient whose chest pain has settled is discharged, give clear verbal and written advice to call an emergency ambulance immediately (and not drive themselves) if pain returns and lasts more than 15 minutes, spreads to the arm, jaw or back, or comes with cold sweat, nausea or breathlessness. Explain the expected course, arrange a specific review or follow-up, and document the advice given. Keep a lower threshold for review in people with diabetes, older adults, and those with known cardiac risk factors.",
    category: "safety-net",
    source: "NICE CG95; NICE safety-netting principles",
    keywords: ["safety netting","chest pain","sakit dada","return advice","follow-up","when to call 999","emergency ambulance","worsening"],
  },
  {
    id: "thunderclap-headache-treat-as-bleed-refer-99",
    title: "Thunderclap headache — treat as bleed, refer 999",
    text: "A sudden severe headache peaking within about 5 minutes (\"worst ever\", like a blow to the head) is a thunderclap headache — treat as subarachnoid haemorrhage until proven otherwise and admit as an emergency (999). Other secondary-headache red flags include new focal neurological deficit, seizure, reduced consciousness, fever with neck stiffness, or a new headache with age over 50, immunosuppression or known cancer. CT head sensitivity is highest within 6 hours of onset, so refer without delay rather than trialling analgesia.",
    category: "red-flags",
    source: "NICE NG228 (subarachnoid haemorrhage); NICE CKS Headache",
    keywords: ["thunderclap headache","sudden severe headache","worst headache ever","subarachnoid haemorrhage","SAH","sakit kepala teruk mengejut","headache red flags","refer 999"],
  },
  {
    id: "meningitis-meningococcal-red-flags-999-now",
    title: "Meningitis / meningococcal red flags — 999 now",
    text: "Suspect bacterial meningitis with fever, headache, neck stiffness (kaku tengkuk) and altered consciousness or confusion — refer immediately (999). A non-blanching petechial or purpuric rash (does not fade under a glass), photophobia, or pale/mottled/cold skin suggests meningococcal septicaemia; do not wait for a rash or for all features before sending in. Give parenteral benzylpenicillin or ceftriaxone at the earliest opportunity, but only if it does not delay urgent transfer.",
    category: "red-flags",
    source: "NICE NG240 (bacterial meningitis and meningococcal disease); Meningitis Research Foundation",
    keywords: ["meningitis","meningococcal disease","non-blanching rash","ruam tidak pudar","neck stiffness","kaku tengkuk","photophobia","petechiae purpura","sepsis","999"],
  },
  {
    id: "stroke-fast-be-fast-call-999-immediately",
    title: "Stroke — FAST/BE-FAST, call 999 immediately",
    text: "Any sudden Face droop, Arm weakness or Speech disturbance is a FAST-positive stroke; BE-FAST adds sudden Balance loss and Eye/visual loss — call 999 immediately, record the time the patient was last known well, and do not drive them in yourself. Stroke is time-critical: thrombolysis can be given up to 4.5 hours from onset and thrombectomy later in selected patients. Check a capillary glucose to exclude hypoglycaemia, a common stroke mimic.",
    category: "referral",
    source: "NICE NG128 (stroke and TIA in over 16s); Stroke Association FAST",
    keywords: ["stroke","FAST","BE-FAST","face droop","arm weakness","slurred speech","strok","angin ahmar","thrombolysis","call 999"],
  },
  {
    id: "syncope-cardiac-red-flags-when-to-refer",
    title: "Syncope — cardiac red flags & when to refer",
    text: "Most faints are vasovagal (the 3 P's: upright Posture/prolonged standing, a Provoking trigger such as pain or heat, and a Prodrome such as sweating), but diagnose this only after excluding high-risk features. Refer urgently to cardiology for any red flag: syncope on exertion or while lying flat, no warning at all, palpitations or chest pain beforehand, known structural heart disease, or a family history of sudden cardiac death under 40. Do a 12-lead ECG after any transient loss of consciousness — conduction block or other ECG abnormality is a red flag, as are recurrent episodes, injury, or new cardiac symptoms.",
    category: "referral",
    source: "NICE CG109 (transient loss of consciousness in over 16s)",
    keywords: ["syncope","fainting","pengsan","transient loss of consciousness","blackout","exertional syncope","palpitations","ECG","sudden cardiac death","when to refer"],
  },
  {
    id: "seizure-status-epilepticus-999-criteria",
    title: "Seizure — status epilepticus & 999 criteria",
    text: "Call 999 if a convulsion lasts 5 minutes or longer (status epilepticus), if seizures recur without recovery in between, or for a first-ever seizure, injury, breathing difficulty, pregnancy, or a seizure in water. During the seizure protect the head, do not restrain the person or put anything in the mouth, and place them in the recovery position once the movements stop. Refer any first seizure for urgent first-fit/neurology assessment and safety-net about driving and unsupervised swimming or bathing.",
    category: "red-flags",
    source: "NICE NG217 (epilepsies in children, young people and adults); epilepsy first-aid guidance",
    keywords: ["seizure","fit","sawan","status epilepticus","first seizure","convulsion","epilepsy","recovery position","5 minutes","999"],
  },
  {
    id: "acute-abdominal-pain-surgical-red-flags-acut",
    title: "Acute abdominal pain — surgical red flags (acute abdomen)",
    text: "Refer/admit urgently for a surgical opinion if abdominal pain (sakit perut) is severe or worsening with signs of peritonism (board-like rigidity, guarding, rebound tenderness) or a distended, silent abdomen. Treat as an emergency any pain with haemodynamic instability (tachycardia, hypotension) or features of perforation, bowel obstruction, or mesenteric ischaemia (sudden severe pain out of proportion to examination). Sudden severe abdominal/back pain with collapse or a pulsatile mass in an older patient may be a leaking abdominal aortic aneurysm — call emergency services immediately.",
    category: "red-flags",
    source: "NICE CKS; MOH Malaysia CPG",
    keywords: ["abdominal pain","acute abdomen","sakit perut","peritonitis","guarding","rebound tenderness","bowel obstruction","perforation","AAA","surgical referral"],
  },
  {
    id: "gi-bleeding-melaena-haematemesis-same-day-em",
    title: "GI bleeding (melaena / haematemesis) — same-day emergency admission",
    text: "Haematemesis (muntah darah), 'coffee-ground' vomit, or melaena (black, tarry stool / najis hitam) indicates gastrointestinal bleeding — arrange emergency same-day hospital admission, not community management. Escalate fastest with signs of shock: tachycardia, hypotension or postural drop, pallor, sweating, syncope, or ongoing visible bleeding. Ask about NSAIDs, aspirin, anticoagulants, heavy alcohol use and known liver disease/varices, as these raise both bleeding risk and mortality.",
    category: "referral",
    source: "NICE (acute upper GI bleeding); NICE CKS",
    keywords: ["GI bleeding","melaena","haematemesis","muntah darah","najis hitam","coffee-ground vomit","black tarry stool","upper GI bleed","shock","urgent admission"],
  },
  {
    id: "dyspepsia-reflux-alarm-features-needing-urge",
    title: "Dyspepsia / reflux — alarm features needing urgent endoscopy",
    text: "Refer on the urgent suspected-cancer pathway for direct-access upper GI endoscopy (ideally within 2 weeks) for dysphagia at any age, or for those aged 55 and over with weight loss plus upper abdominal pain, reflux or dyspepsia. Also refer urgently for an upper abdominal mass, unexplained iron-deficiency anaemia, or persistent vomiting. Any new alarm symptom, or dyspepsia not settling despite treatment, warrants review and consideration of endoscopy.",
    category: "referral",
    source: "NICE NG12 (suspected cancer referral); NICE CKS (dyspepsia)",
    keywords: ["dyspepsia","reflux","GORD","dysphagia","weight loss","upper GI cancer","iron-deficiency anaemia","endoscopy","OGD","2-week referral","alarm symptoms"],
  },
  {
    id: "vomiting-dehydration-in-adults-safety-nettin",
    title: "Vomiting & dehydration in adults — safety-netting",
    text: "Most acute gastroenteritis (muntah, cirit-birit) is self-limiting — manage with oral rehydration using small, frequent sips or oral rehydration salts (ORS), and safety-net clearly. Seek urgent review if the person cannot keep any fluids down, has reduced or very dark urine, dizziness/confusion, blood in vomit or stool, severe or localised abdominal pain, high fever, or symptoms persisting beyond about 48–72 hours. Have a lower threshold to assess older, frail, pregnant, diabetic or immunocompromised patients, who dehydrate and deteriorate faster.",
    category: "safety-net",
    source: "NICE CKS (gastroenteritis); WHO (oral rehydration)",
    keywords: ["vomiting","muntah","dehydration","dehidrasi","gastroenteritis","diarrhoea","cirit-birit","oral rehydration salts","ORS","safety netting","reduced urine output"],
  },
  {
    id: "child-with-vomiting-diarrhoea-dehydration-sh",
    title: "Child with vomiting/diarrhoea — dehydration & shock red flags",
    text: "In a young child with gastroenteritis, red-flag signs of clinical dehydration include altered or decreased responsiveness, sunken eyes, tachycardia, tachypnoea and reduced skin turgor — refer for urgent assessment. Signs of shock (mottled or pale skin, cold peripheries, prolonged capillary refill, weak pulses, hypotension) need emergency admission. Green/bilious vomiting, blood in stool, or severe localised abdominal pain suggest a surgical cause such as obstruction or intussusception — refer urgently; encourage ORS and continued breastfeeding, and safety-net on reduced wet nappies/urine output.",
    category: "paediatric",
    source: "NICE CG84 (diarrhoea & vomiting in under 5s); NICE CKS",
    keywords: ["child fever vomiting","paediatric dehydration","gastroenteritis children","bilious vomiting","green vomit","intussusception","shock","skin turgor","sunken eyes","wet nappies","cirit-birit kanak-kanak","ORS"],
  },
  {
    id: "feverish-child-under-5-red-flag-features-ref",
    title: "Feverish child under 5 — red-flag features (refer urgently)",
    text: "In a child under 5 with fever (demam), arrange urgent same-day assessment if any 'red' traffic-light feature is present: pale/mottled/ashen/blue skin, no response to social cues, unrousable or won't stay awake, weak/high-pitched/continuous cry, grunting, respiratory rate over 60/min, moderate-to-severe chest indrawing, reduced skin turgor, non-blanching rash, bulging fontanelle, neck stiffness, status epilepticus, or focal seizures/neurology. Any infant under 3 months with a temperature of 38C or higher is high risk on age alone. 'Amber' features (poor feeding, reduced urine, capillary refill 3s or more, parent-reported pallor, SpO2 95% or less, fever 5 days or more) warrant face-to-face review and clear safety-netting.",
    category: "red-flags",
    source: "NICE NG143 (Fever in under 5s) traffic-light system",
    keywords: ["fever","demam","child under 5","traffic light","red flags","respiratory rate","grunting","when to refer","high risk","capillary refill"],
  },
  {
    id: "non-blanching-rash-fever-meningococcal-emerg",
    title: "Non-blanching rash + fever — meningococcal emergency",
    text: "Fever with a non-blanching rash (ruam yang tidak pudar bila ditekan) that does not fade under gentle glass/tumbler pressure is a red flag for meningococcal sepsis — treat as an emergency and arrange immediate hospital transfer, especially if the child looks ill, the rash is spreading or has lesions over 2 mm (purpura), capillary refill is 3s or more, or there is neck stiffness or altered consciousness. Meningococcal disease can progress from well-looking to life-threatening within hours, so do not wait for further signs. Give a single pre-hospital dose of parenteral benzylpenicillin (or cefotaxime/ceftriaxone) before transfer, but only if it does not delay it.",
    category: "red-flags",
    source: "NICE NG143; NICE meningitis (bacterial) and meningococcal septicaemia guidance",
    keywords: ["non-blanching rash","ruam","petechiae","purpura","meningococcal","meningitis","septicaemia","glass test","fever","demam","emergency"],
  },
  {
    id: "dehydration-in-the-febrile-child-assess-and-",
    title: "Dehydration in the febrile child — assess and when to refer",
    text: "Assess hydration in every febrile child: reduced urine output or fewer wet nappies, dry mouth, sunken eyes, absent tears, poor feeding and a capillary refill of 3s or more are warning signs of dehydration (dehidrasi). Reduced skin turgor, a sunken fontanelle, mottled skin or a drowsy/unrousable child suggest significant dehydration or shock and need urgent referral for assessment and rehydration. Encourage regular fluids or oral rehydration solution, continue breastfeeding, and safety-net to return promptly if the child cannot keep fluids down or is passing very little urine.",
    category: "paediatric",
    source: "NICE NG143 (Fever in under 5s); WHO IMCI",
    keywords: ["dehydration","dehidrasi","urine output","sunken eyes","skin turgor","fontanelle","oral rehydration","poor feeding","when to refer","demam"],
  },
  {
    id: "febrile-seizure-kejang-demam-when-to-call-an",
    title: "Febrile seizure (kejang demam) — when to call an ambulance / refer",
    text: "Most febrile seizures in children aged 6 months to 5 years are simple (generalised, under 15 minutes, once per illness, with full recovery) and benign. Call an ambulance or attend the emergency department if a seizure lasts longer than 5 minutes, there are repeated or focal seizures, the child does not regain consciousness, or there is breathing difficulty, a non-blanching rash, neck stiffness or a bulging fontanelle — features suggesting a complex seizure or meningitis/encephalitis. Refer a first febrile seizure, any complex features, age under 18 months, or diagnostic uncertainty, and advise parents that antipyretics do not prevent recurrence.",
    category: "safety-net",
    source: "NICE CKS (Febrile seizure); MOH Malaysia / RCH guidance",
    keywords: ["febrile seizure","febrile convulsion","kejang demam","sawan","fits","complex seizure","when to refer","ambulance","meningitis","demam"],
  },
  {
    id: "dengue-warning-signs-in-children-demam-dengg",
    title: "Dengue warning signs in children (demam denggi) — admit",
    text: "In a child with dengue, the critical (defervescence) phase around days 3-7 is when plasma leakage occurs — admit if any WHO warning sign appears: severe or persistent abdominal pain/tenderness, persistent vomiting, clinical fluid accumulation (ascites/pleural effusion), mucosal bleeding, lethargy or restlessness, liver enlargement over 2 cm, or a rising haematocrit with a rapid fall in platelets. Also admit infants and any child who cannot tolerate oral fluids or has reduced urine output. Warning signs often appear as the fever settles, so review daily during the febrile illness and safety-net carefully.",
    category: "red-flags",
    source: "MOH Malaysia CPG (Management of Dengue Infection, paediatric); WHO 2009 dengue classification",
    keywords: ["dengue","demam denggi","warning signs","abdominal pain","persistent vomiting","plasma leakage","haematocrit","platelets","admit","mucosal bleeding"],
  },
  {
    id: "antipyretics-in-the-febrile-child-safe-use",
    title: "Antipyretics in the febrile child — safe use",
    text: "Use paracetamol or ibuprofen only if a feverish child is distressed, not routinely to lower temperature, and never to try to prevent febrile seizures; dose paracetamol by weight (about 15 mg/kg per dose). Do not give paracetamol and ibuprofen at the same time — consider switching to the alternative agent only if distress persists or recurs before the next dose is due. Avoid aspirin in children under 16 (Reye's syndrome), and in suspected dengue (demam denggi) avoid ibuprofen/NSAIDs and aspirin because of bleeding risk — use paracetamol alone.",
    category: "medication-safety",
    source: "NICE NG143 (Fever in under 5s); MOH Malaysia dengue CPG",
    keywords: ["paracetamol","ibuprofen","antipyretic","NSAID","aspirin","Reye's syndrome","dengue","medication safety","febrile seizure","weight-based dosing"],
  },
  {
    id: "urti-usually-viral-when-to-worry",
    title: "URTI — usually viral; when to worry",
    text: "Most upper respiratory tract infections (batuk-selsema) are viral and self-limiting, so antibiotics are not routinely needed. Safety-net: return if breathing becomes difficult (sesak nafas), symptoms are not improving after about a week, fever is high or persistent, or the person becomes systemically very unwell. With a sore throat, urgent same-day assessment is needed for drooling, stridor, difficulty swallowing, trismus, or one-sided neck/throat swelling — possible peritonsillar abscess or epiglottitis.",
    category: "safety-net",
    source: "NICE CKS",
    keywords: ["URTI","upper respiratory tract infection","common cold","batuk selsema","selsema","sore throat","sakit tekak","viral","antibiotics","safety-netting","FeverPAIN"],
  },
  {
    id: "uti-when-to-refer-and-red-flags",
    title: "UTI — when to refer and red flags",
    text: "Uncomplicated lower UTI (jangkitan air kencing / kencing sakit) in non-pregnant women is usually managed in primary care. Arrange urgent assessment or admission for suspected pyelonephritis or sepsis: loin/flank pain, high fever, rigors, vomiting, or systemic illness. Treat UTI in pregnancy, men, children, catheterised, or recurrent cases as higher-risk — send a urine culture, lower your threshold to refer, and in men also consider prostatitis or a sexually transmitted infection.",
    category: "referral",
    source: "NICE CKS",
    keywords: ["UTI","urinary tract infection","jangkitan air kencing","kencing sakit","pyelonephritis","sepsis","pregnancy","loin pain","haematuria","men","referral"],
  },
  {
    id: "gastroenteritis-dehydration-red-flags-safety",
    title: "Gastroenteritis — dehydration red flags & safety-netting",
    text: "Most acute gastroenteritis (cirit-birit / muntah) is viral and self-limiting; the priority is rehydration with oral rehydration solution (ORS), small frequent sips, and continuing food as tolerated. Seek urgent care for dehydration red flags: markedly reduced urine output, dizziness or confusion, cold/mottled skin, rapid heartbeat, or inability to keep any fluids down. Also review for blood in the stool, severe or localised abdominal pain, high fever, symptoms beyond about a week, or higher-risk patients (frail/elderly, immunocompromised, or recent antibiotics — consider C. difficile).",
    category: "safety-net",
    source: "NICE CKS; WHO (oral rehydration)",
    keywords: ["gastroenteritis","diarrhoea","cirit-birit","muntah","vomiting","dehydration","ORS","oral rehydration","bloody diarrhoea","safety-netting"],
  },
  {
    id: "hypertension-review-basics-bp-targets",
    title: "Hypertension review — basics & BP targets",
    text: "Hypertension (darah tinggi) is persistent BP of 140/90 mmHg or higher; confirm with repeated readings and home or ambulatory monitoring where possible, rather than acting on a single high reading. A general clinic target is below 140/90 mmHg, with a tighter target around 130/80 mmHg commonly used in diabetes, chronic kidney disease, or proteinuria. Reviews should reinforce lifestyle (salt reduction, weight, activity, smoking cessation), check adherence, and assess cardiovascular risk and end-organ effects such as renal function and urine protein.",
    category: "condition",
    source: "MOH Malaysia CPG (Hypertension); NICE",
    keywords: ["hypertension","high blood pressure","darah tinggi","tekanan darah tinggi","BP target","blood pressure","CKD","diabetes","lifestyle","review"],
  },
  {
    id: "type-2-diabetes-review-what-to-check",
    title: "Type 2 diabetes review — what to check",
    text: "A structured diabetes (kencing manis) review covers glycaemic control (HbA1c with an individualised target, typically every 3–6 months until stable then around 6-monthly) alongside blood pressure, lipids, and weight. Screen at least yearly for complications: feet (sensation, pulses, ulcers), eyes (retinal screening), and kidneys (renal function plus urine albumin/ACR). Reinforce lifestyle, adherence, and hypoglycaemia awareness, and refer for foot ulceration, sight-threatening retinopathy, or declining kidney function.",
    category: "condition",
    source: "MOH Malaysia CPG (Type 2 Diabetes); NICE",
    keywords: ["diabetes","type 2 diabetes","kencing manis","HbA1c","diabetic foot","retinopathy","nephropathy","ACR","annual review","complications"],
  },
  {
    id: "paracetamol-safe-maximum-dose-adults",
    title: "Paracetamol — safe maximum dose (adults)",
    text: "For a healthy adult, paracetamol (acetaminophen) is 1 g up to four times daily, to a maximum of 4 g in 24 hours; do not exceed this or combine with other paracetamol-containing products (e.g. cold-and-flu combinations). Use a lower maximum, guided by clinical judgement, in low body weight (under 50 kg), significant liver disease, chronic alcohol use, frailty, or malnutrition. Overdose can cause serious liver injury with few early symptoms — treat any suspected overdose urgently per poisons guidance (e.g. N-acetylcysteine).",
    category: "medication-safety",
    source: "BNF; NICE CKS",
    keywords: ["paracetamol","acetaminophen","panadol","ubat demam","maximum dose","4g","overdose","liver","hepatotoxicity","N-acetylcysteine","medication safety"],
  },
];
